# Reference:
# https://github.com/marketplace/actions/build-and-push-docker-images
name: docker

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: evertras
          password: ${{ secrets.DOCKER_API_KEY }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: evertras/cynomys:${GITHUB_REF##*/},evertras/cynomys:latest